steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'us-central1-docker.pkg.dev/ldmr-velocitymatch/lmdr-repo/lmdr-notifications-service:$COMMIT_SHA'
      - '-f'
      - 'services/notifications-service/Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/ldmr-velocitymatch/lmdr-repo/lmdr-notifications-service:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - lmdr-notifications-service
      - '--image=us-central1-docker.pkg.dev/ldmr-velocitymatch/lmdr-repo/lmdr-notifications-service:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--service-account=lmdr-services-sa@ldmr-velocitymatch.iam.gserviceaccount.com'
      - '--add-cloudsql-instances=ldmr-velocitymatch:us-central1:lmdr-postgres'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--memory=512Mi'
      - '--set-env-vars=NODE_ENV=production,SERVICE_NAME=lmdr-notifications-service,PG_DATABASE=lmdr,PG_USER=lmdr_user,CLOUD_SQL_INSTANCE=ldmr-velocitymatch:us-central1:lmdr-postgres'
      - '--set-secrets=SENDGRID_API_KEY=lmdr-sendgrid-api-key:latest,TWILIO_ACCOUNT_SID=lmdr-twilio-account-sid:latest,TWILIO_AUTH_TOKEN=lmdr-twilio-auth-token:latest,PG_PASSWORD=lmdr-pg-password:latest'
images:
  - 'us-central1-docker.pkg.dev/ldmr-velocitymatch/lmdr-repo/lmdr-notifications-service:$COMMIT_SHA'
