#!/usr/bin/env python3
"""Cross-reference 66 migration error tables against real Airtable tables."""

error_tables = {
    "complianceReports": "v2_Compliance Reports",
    "scheduledReports": "v2_Scheduled Reports",
    "restStopConditionReports": "v2_Rest Stop Condition Reports",
    "weatherAlerts": "v2_Weather Alerts",
    "driverWeatherSubscriptions": "v2_Driver Weather Subscriptions",
    "roadConditions": "v2_Road Conditions",
    "truckRestrictions": "v2_Truck Restrictions",
    "driverConditionReports": "v2_Driver Condition Reports",
    "apiPartners": "v2_API Partners",
    "apiSubscriptions": "v2_API Subscriptions",
    "apiUsage": "v2_API Usage",
    "apiRequestLog": "v2_API Request Log",
    "apiProducts": "v2_API Products",
    "apiAlertSubscriptions": "v2_API Alert Subscriptions",
    "apiWebhookDeliveries": "v2_API Webhook Deliveries",
    "mentorMatches": "v2_Mentor Matches",
    "aiProviderCosts": "v2_AI Provider Costs",
    "costOptimizerConfig": "v2_Cost Optimizer Config",
    "anomalyAlerts": "v2_Anomaly Alerts",
    "anomalyRules": "v2_Anomaly Rules",
    "baselineMetrics": "v2_Baseline Metrics",
    "revenueMetrics": "v2_Revenue Metrics",
    "billingAdjustments": "v2_Billing Adjustments",
    "invoices": "v2_Invoices",
    "commissions": "v2_Commissions",
    "salesReps": "v2_Sales Reps",
    "commissionRules": "v2_Commission Rules",
    "supportTickets": "v2_Support Tickets",
    "ticketComments": "v2_Ticket Comments",
    "ticketTags": "v2_Ticket Tags",
    "knowledgeArticles": "v2_Knowledge Articles",
    "articleCategories": "v2_Article Categories",
    "articleVersions": "v2_Article Versions",
    "npsResponses": "v2_NPS Responses",
    "surveyConfig": "v2_Survey Config",
    "npsTrends": "v2_NPS Trends",
    "chatSessions": "v2_Chat Sessions",
    "chatMessages": "v2_Chat Messages",
    "cannedResponses": "v2_Canned Responses",
    "agentMailTenants": "v2_AgentMail Tenants",
    "agentMailInboxes": "v2_AgentMail Inboxes",
    "agentMailThreads": "v2_AgentMail Threads",
    "agentMailMessages": "v2_AgentMail Messages",
    "agentMailDrafts": "v2_AgentMail Drafts",
    "agentMailWebhookEvents": "v2_AgentMail Webhook Events",
    "communicationIdentities": "v2_Communication Identities",
    "communicationMemories": "v2_Communication Memories",
    "communicationLinks": "v2_Communication Links",
    "emailCampaigns": "v2_Email Campaigns",
    "emailSequences": "v2_Email Sequences",
    "emailSequenceEnrollments": "v2_Email Sequence Enrollments",
    "emailMessages": "v2_Email Messages",
    "smsCampaigns": "v2_SMS Campaigns",
    "smsMessages": "v2_SMS Messages",
    "smsOptOuts": "v2_SMS Opt Outs",
    "jobBoardCredentials": "v2_Job Board Credentials",
    "jobApplications": "v2_Job Applications",
    "socialPosts": "v2_Social Posts",
    "socialAccounts": "v2_Social Accounts",
    "socialPostQueue": "v2_Social Post Queue",
    "socialAuditLog": "v2_Social Audit Log",
    "retentionOutcomes": "v2_Retention Outcomes",
    "ragDocuments": "v2_RAG Documents",
    "ragRetrievalLog": "v2_RAG Retrieval Log",
    "ragAnalytics": "v2_RAG Analytics",
    "intentClassificationLog": "v2_Intent Classification Log",
}

# All 255 real Airtable tables from MCP list_tables
real_tables = {
    "Applications", "CDL DRIVERS NJ FB CAMPAIGN", "Carriers (Leads)", "Carriers (Master)",
    "Client Carriers", "Imported table", "Legacy Driver Leads", "Quick APP- JOTFORM",
    "Scored Drivers", "v2_AB Test Assignments", "v2_AB Test Events", "v2_AB Tests",
    "v2_AI Router Config", "v2_AI Usage Log", "v2_Abandonment Email Log",
    "v2_Achievement Definitions", "v2_Admin Users", "v2_Agent Conversations",
    "v2_Agent Evaluations", "v2_Agent Runs", "v2_Agent Steps", "v2_Agent Turns",
    "v2_Announcement Comments", "v2_Announcement Read Receipts", "v2_Approval Gates",
    "v2_Audit Log", "v2_Automation Log", "v2_Autopilot Campaigns", "v2_Autopilot Steps",
    "v2_B2B AI Action Log", "v2_B2B Account Research", "v2_B2B Accounts",
    "v2_B2B Activities", "v2_B2B Analytics Snapshots", "v2_B2B Automation Rules",
    "v2_B2B Call Campaigns", "v2_B2B Calls", "v2_B2B Competitor Intel",
    "v2_B2B Contacts", "v2_B2B Content Cache", "v2_B2B Content Drafts",
    "v2_B2B Emails", "v2_B2B Lead Attribution", "v2_B2B Lead Capture Events",
    "v2_B2B Lead Sources", "v2_B2B Match Signals", "v2_B2B Opportunities",
    "v2_B2B Playbooks", "v2_B2B Sequence Steps", "v2_B2B Sequences",
    "v2_B2B Spend", "v2_B2B Tasks", "v2_B2B Text Messages", "v2_B2B Value Props",
    "v2_Background Checks", "v2_Badge Definitions", "v2_Best Practices Guides",
    "v2_Billing History", "v2_Blog Categories", "v2_Blog Posts", "v2_CSA Score History",
    "v2_Call Feedback", "v2_Call Outcomes", "v2_Capacity Plans",
    "v2_Carrier Announcements", "v2_Carrier Documents", "v2_Carrier Driver Outreach",
    "v2_Carrier Driver Views", "v2_Carrier Enrichments", "v2_Carrier Hiring Preferences",
    "v2_Carrier Notification Settings", "v2_Carrier Onboarding", "v2_Carrier Reviews",
    "v2_Carrier Staffing Requests", "v2_Carrier Testimonials", "v2_Carriers",
    "v2_Case Studies", "v2_Challenge Definitions", "v2_Checkout Abandonment",
    "v2_Company Milestones", "v2_Compendium Entries", "v2_Competitor Intel",
    "v2_Compliance Alerts", "v2_Compliance Events", "v2_Compliance Guides",
    "v2_Document Requests", "v2_Driver Achievements", "v2_Driver Activity Feed",
    "v2_Driver Carrier Interests", "v2_Driver Challenges", "v2_Driver Conversations",
    "v2_Driver Expenses", "v2_Driver Job Preferences", "v2_Driver Jobs",
    "v2_Driver Lifecycle Events", "v2_Driver Locations", "v2_Driver Match Feedback",
    "v2_Driver Matches", "v2_Driver Messages", "v2_Driver Notification Preferences",
    "v2_Driver Notifications", "v2_Driver Performance", "v2_Driver Profiles",
    "v2_Driver Progression", "v2_Driver Quick Responses", "v2_Driver Recognitions",
    "v2_Driver Referrals", "v2_Driver Saved Jobs", "v2_Driver Scores",
    "v2_Driver Settlements", "v2_Driver Survey Requests", "v2_Driver Survey Responses",
    "v2_Driver Surveys", "v2_Driver Tax Summary", "v2_Driver Testimonials",
    "v2_Driver-Carrier Interests", "v2_Drug Tests", "v2_E-Sign Requests",
    "v2_ELD Connections", "v2_ELD Logs", "v2_Email Send Logs", "v2_Email Templates",
    "v2_Equipment Assets", "v2_Equipment Assignments", "v2_Event Leaderboard",
    "v2_Event Participants", "v2_Exit Surveys", "v2_FAQs", "v2_FMCSA Safety Data",
    "v2_Feature Adoption Logs", "v2_Feature Flags", "v2_Feature Funnels",
    "v2_Feature Metrics Daily", "v2_Feature Registry", "v2_Feedback Requests",
    "v2_Flag Evaluation Logs", "v2_Fleet Drivers", "v2_Forum Categories",
    "v2_Forum Posts", "v2_Forum Replies", "v2_Forum Reports", "v2_Forum Threads",
    "v2_Fuel Cards", "v2_Fuel Prices", "v2_Funnel Events", "v2_Gamification Events",
    "v2_HOS Records", "v2_HOS Violations", "v2_Health Resources", "v2_Health Tips",
    "v2_Hiring Forecasts", "v2_Incident Log", "v2_Incident Reports",
    "v2_Industry Comparisons", "v2_Intervention Log", "v2_Intervention Templates",
    "v2_Interviews", "v2_Job Postings", "v2_Leaderboard Snapshots",
    "v2_Lifecycle Events", "v2_Market Intelligence", "v2_Market Signals",
    "v2_Match Events", "v2_Match Notification Log", "v2_Match Quality Bonuses",
    "v2_Match Subscription Alerts", "v2_Match Subscriptions", "v2_Member Activity",
    "v2_Member Notifications", "v2_Mentor Profiles", "v2_Mentorship Connections",
    "v2_Messages", "v2_Meta Ad Accounts", "v2_Meta Ad Mirror", "v2_Meta Ad Set Mirror",
    "v2_Meta Async Report Jobs", "v2_Meta Attribution Links", "v2_Meta Campaign Mirror",
    "v2_Meta Creative Mirror", "v2_Meta Error Events", "v2_Meta Governance Policies",
    "v2_Meta Insights Daily", "v2_Meta Insights Intraday", "v2_Meta Integrations",
    "v2_Meta Mutation Audit", "v2_Meta Optimization Actions", "v2_Meta Rate Limit Events",
    "v2_Notification Logs", "v2_Notification Queue", "v2_Notification Rules",
    "v2_Onboarding Workflows", "v2_Orientation Slots", "v2_Outreach Templates",
    "v2_Parking Favorites", "v2_Parking Locations", "v2_Parking Reports",
    "v2_Partner Onboarding", "v2_Pet Friendly Locations", "v2_Pet Friendly Reviews",
    "v2_Pipeline Automation Rules", "v2_Pipeline Events", "v2_Platform Settings",
    "v2_Policy Acknowledgments", "v2_Policy Documents", "v2_Pricing Tiers",
    "v2_Profile Views", "v2_Prompt Library", "v2_Qualification Files",
    "v2_Recruiter Badges", "v2_Recruiter Carriers", "v2_Recruiter Challenges",
    "v2_Recruiter Profiles", "v2_Recruiter Progression", "v2_Recruiter Scorecards",
    "v2_Recruiting Spend", "v2_Remediation Plans", "v2_Rest Stop Reviews",
    "v2_Retention Interventions", "v2_Retention Risk Logs", "v2_Retention Watchlist",
    "v2_Reverse Alerts", "v2_Road Hazard Reports", "v2_Road Utility Cache",
    "v2_Run Outcomes", "v2_Saved Search Alerts", "v2_Saved Searches",
    "v2_Search Jobs", "v2_Seasonal Events", "v2_Service Features",
    "v2_Settlement Disputes", "v2_Social Credentials", "v2_Source Attribution",
    "v2_Stripe Events", "v2_Subscriptions", "v2_Survey Definitions",
    "v2_Survey Responses", "v2_System Alerts", "v2_System Errors",
    "v2_System Logs", "v2_System Metrics", "v2_System Traces",
    "v2_Tax Reference Data", "v2_Team Members", "v2_Termination Logs",
    "v2_Training Courses", "v2_Training Enrollments", "v2_Training Progress",
    "v2_User Throttle State", "v2_Voice Agent Templates", "v2_Voice Assistants",
    "v2_Voice Call Logs", "v2_Voice Campaign Contacts", "v2_Voice Campaigns",
    "v2_Weather Alert Subscriptions", "v2_Weigh Station Status",
}

exists = []
missing = []

for key, airtable_name in error_tables.items():
    if airtable_name in real_tables:
        exists.append((key, airtable_name))
    else:
        missing.append((key, airtable_name))

print(f"EXIST in Airtable (rate-limited, should retry): {len(exists)}")
print("=" * 60)
for k, n in exists:
    print(f"  {k:40s} -> {n}")

print(f"\nDO NOT EXIST in Airtable (safe to skip): {len(missing)}")
print("=" * 60)
for k, n in missing:
    print(f"  {k:40s} -> {n}")
